# Generated by Django 6.0.2 on 2026-02-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_estudiante',
            field=models.CharField(blank=True, choices=[('C', 'Colegio'), ('U', 'Universidad')], max_length=1, null=True),
        ),
    ]
