# Generated by Django 6.0.2 on 2026-02-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_tipo_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_estudiante',
            field=models.CharField(choices=[('C', 'Colegio'), ('U', 'Universidad')], max_length=1, null=True),
        ),
    ]
