# Generated by Django 6.0.2 on 2026-02-27 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_tipo_estudiante'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUniversitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universidad', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('total_semestres', models.PositiveIntegerField()),
                ('semestre_actual', models.PositiveIntegerField()),
                ('creditos_para_graduarse', models.PositiveIntegerField()),
                ('creditos_aprobados', models.PositiveIntegerField(default=0)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_universitario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Universitario',
                'verbose_name_plural': 'Perfiles Universitarios',
            },
        ),
    ]
