# Generated by Django 6.0.2 on 2026-03-02 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_perfiluniversitario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilSecundaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_instituto', models.CharField(max_length=100)),
                ('curso_actual', models.CharField(max_length=100)),
                ('total_de_periodos', models.PositiveIntegerField()),
                ('periodo_actual', models.PositiveIntegerField()),
                ('total_de_materias', models.PositiveIntegerField()),
                ('total_de_materias_para_aprobacion', models.PositiveIntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_secundaria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil Secundaria',
                'verbose_name_plural': 'Perfiles Secundaria',
            },
        ),
    ]
