# Generated by Django 6.0.2 on 2026-03-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_bloqueado_hasta_usuario_intentos_fallidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiluniversitario',
            name='total_semestres',
        ),
        migrations.AddField(
            model_name='perfiluniversitario',
            name='creditos_maximos_por_semestre',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfiluniversitario',
            name='creditos_minimos_por_semestre',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfiluniversitario',
            name='promedio_minimo_carrera',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=4),
        ),
    ]
