# Generated by Django 6.0.2 on 2026-03-05 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_perfiluniversitario_total_semestres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creditos', models.PositiveIntegerField()),
                ('total_notas', models.PositiveIntegerField()),
                ('escala_notas', models.CharField(choices=[('5.0', 'Sobre 5.0'), ('10.0', 'Sobre 10.0'), ('100', 'Sobre 100')], default='5.0', max_length=5)),
                ('nota_minima_aprobacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('aprobada', 'Aprobada'), ('perdida', 'Perdida')], default='activa', max_length=10)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_obtenido', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('recordatorio', models.DateTimeField(blank=True, null=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='usuarios.materia')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('completado', 'Completado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='usuarios.perfiluniversitario')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['numero'],
                'unique_together': {('perfil', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='materia',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='usuarios.semestre'),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=5)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('recordatorio', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('entregada', 'Entregada'), ('vencida', 'Vencida')], default='pendiente', max_length=10)),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='usuarios.semestre')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
            },
        ),
    ]
