# Generated by Django 6.0.2 on 2026-03-11 11:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_materia_nota_semestre_materia_semestre_tarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=5),
        ),
        migrations.AddField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('examen', 'Examen'), ('parcial', 'Parcial'), ('tarea', 'Tarea'), ('proyecto', 'Proyecto'), ('quiz', 'Quiz'), ('otro', 'Otro')], default='otro', max_length=10),
        ),
        migrations.AddField(
            model_name='perfiluniversitario',
            name='anno_ingreso',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfiluniversitario',
            name='escala_notas',
            field=models.CharField(default='5.0', max_length=5),
        ),
        migrations.AddField(
            model_name='perfiluniversitario',
            name='facultad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='perfiluniversitario',
            name='modalidad',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='perfiluniversitario',
            name='nota_minima_global',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='perfiluniversitario',
            name='total_semestres',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='materia',
            name='color',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
        migrations.AlterField(
            model_name='nota',
            name='recordatorio',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ClaseHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=100)),
                ('color', models.CharField(default='#2563eb', max_length=7)),
                ('dia', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado')])),
                ('hora_inicio', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('duracion', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)])),
                ('salon', models.CharField(blank=True, max_length=100)),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clases_horario', to='usuarios.materia')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='usuarios.perfiluniversitario')),
            ],
            options={
                'verbose_name': 'Clase en Horario',
                'verbose_name_plural': 'Clases en Horario',
                'ordering': ['dia', 'hora_inicio'],
            },
        ),
    ]
